/**
 * Lookup table that is used by newtonianApproximation.c as a speedup
 * @author Oliver Krauss @date 21 Aug 2019
 */

#ifndef USERPROVIDEDFN_LOOKUPTABLE_H
#define USERPROVIDEDFN_LOOKUPTABLE_H

/**
 * lower end of the range the lookup table was generated for
 */
extern const double lower_end;

/**
 * higher end of the range the lookup table was used for
 */
extern const double higher_end;

/**
 * Helper constant equals the size of the lookup table
 */
extern const int table_size;

/**
 * Lookup table for the ranges between lower_end and higher_end.
 * DO NOT MODIFY > this is generated by CMA_ES
 */
extern double lookupTable[512];

#endif //USERPROVIDEDFN_LOOKUPTABLE_H
